### ISSUE TITLE
Issue with Example Code

### ISSUE THREAD

**Issue by mhudecheck** [chrisvwn/Rnightlights#3]
I'm trying to run through the introductory code.  However, I keep on getting the following error:

`Error in file.rename(file.path(getNlDir("dirNlTiles"), tgzAvgRadFilename),  : 
  'from' and 'to' are of different lengths`

The code I'm running is: 

`lowestAdmLevelStats <- getCtryNlData(ctryCode = 'KEN', 
                                     nlType = "VIIRS", 
                                     nlPeriods = nlRange("201401", "201412"), 
                                     ignoreMissing=FALSE')`

**Comment by chrisvwn** [comment]
@mhudecheck This is caused by a change in the naming of the files inside the .tgz tiles (after they trimmed the number of decimal places in the rasters to 100). The update is on the way to CRAN but in the meantime you can use the development version. You can install the dev version using:

`devtools::install_github("chrisvwn/Rnightlights")`

**Comment by mhudecheck** [comment]
@chrisvwn It looks like it's working now.  Appreciate the quick reply & fix!!! 👍
