### ISSUE TITLE
How to specify time periods for Daily VIIRS

### ISSUE THREAD

**Issue by lynham** [chrisvwn/Rnightlights#38]
Hi Chris, great package, _asante sana!_

I'm in running into a problem when I try to get daily VIIRS data. I don't seem to be able to specify the time periods correctly and I can't find any examples in your documentation. I would like to get daily data for 3-4 days. I altered your demonstration code as below and get the accompanying error message:

> highestAdmLevelStats <- getCtryNlData(ctryCode = "KEN", 
                                      admLevel = "highest",
                                       nlType = "VIIRS.D", 
                                       nlPeriods = nlRange("20140101", "20140102","VIIRS.D"), 
                                       nlStats = list("sum",na.rm=TRUE),
                                       ignoreMissing=FALSE)

Error in nlRange("20140101", "20140102", "VIIRS.D") : 
  2019-10-03 13:50:44: Invalid nlPeriod detected for nlType VIIRS.D

Thanks in advance for your help!

**Comment by chrisvwn** [comment]
Hi @lynham. Karibu sana! :)

You are using it right. The only problem is that the first daily VIIRS data was made available about `20171120` so we use that as the first date. However, due to the size of the data the tiles are kept for about 2 months only. So, try dates within the previous two months. See this page for available data: [https://ngdc.noaa.gov/eog/viirs/download_ut_mos.html](https://ngdc.noaa.gov/eog/viirs/download_ut_mos.html)

I think I will modify the package to query and report available data if the requested data is out of range.

**Comment by lynham** [comment]
Thanks Chris. I was able to get it to work for some dates in September and October 2019. Unfortunately the dates I’m interested in were in March 2019 so I will have to try and find some other way to do the analysis. Thanks again for your prompt response.

**Comment by chrisvwn** [comment]
You're welcome. I hope you find the data you need. All the best!
